const ErrorResponse = require("../utils/errorResponse");

exports.createWallet = async (res, req, next) => {
    try{

    }catch (err) {
        return new ErrorResponse("something went wrong")
    }
}